-- 코드를 입력하세요
# SELECT *
# FROM CAR_RENTAL_COMPANY_CAR A
# JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B, CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
# ON A.CAR_TYPE IN ('세단', 'SUV') 
#     AND LEFT(C.DURATION_TYPE, 2) = '30' 
#     AND 
# WHERE A.CAR_TYPE IN ('세단', 'SUV');

SELECT 
    A.CAR_ID, 
    A.CAR_TYPE,
    ((A.DAILY_FEE * 30) * (100 - C.DISCOUNT_RATE) / 100) AS `FEE`
FROM 
    CAR_RENTAL_COMPANY_CAR A
JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN C 
ON 
    A.CAR_TYPE = C.CAR_TYPE
WHERE 
    A.CAR_TYPE IN ('세단', 'SUV')
    AND C.DURATION_TYPE = '30일 이상'
    AND NOT EXISTS (
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
        WHERE B.CAR_ID = A.CAR_ID
            AND B.START_DATE <= '2022-11-30'
            AND B.END_DATE >= '2022-11-01'
    ) 
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;