-- 코드를 입력하세요
SELECT
    AO.ANIMAL_ID,
    AO.NAME
FROM 
    ANIMAL_OUTS AO
JOIN 
    ANIMAL_INS AI
ON 
    AI.ANIMAL_ID = AO.ANIMAL_ID
ORDER BY 
    AO.DATETIME - AI.DATETIME DESC
FETCH FIRST 2 ROWS ONLY;