-- 코드를 입력하세요
SELECT 
    U.USER_ID AS USER_ID,
    U.NICKNAME AS NICKNAME,
    (U.CITY || ' ' || U.STREET_ADDRESS1 || ' ' || U.STREET_ADDRESS2) AS 전체주소,
    REGEXP_REPLACE(U.TLNO, '([0-9]{2,3})([0-9]{3,4})([0-9]{3,4})', '\1-\2-\3') AS 전화번호
FROM 
    USED_GOODS_USER U
JOIN 
    USED_GOODS_BOARD B
ON 
    U.USER_ID = B.WRITER_ID
GROUP BY 
    U.USER_ID,
    U.NICKNAME,
    U.CITY,
    U.STREET_ADDRESS1,
    U.STREET_ADDRESS2,
    U.TLNO
HAVING 
    COUNT(BOARD_ID) >= 3
ORDER BY U.USER_ID DESC;