-- 코드를 입력하세요
/* SELECT 
    AO.ANIMAL_ID,
    AO.NAME
FROM 
    ANIMAL_OUTS AO
WHERE NOT EXISTS (
    SELECT 1 
    FROM ANIMAL_INS AI
    WHERE AO.ANIMAL_ID = AI.ANIMAL_ID
)
ORDER BY AO.ANIMAL_ID ASC;
*/

SELECT 
    AO.ANIMAL_ID,
    AO.NAME
FROM 
    ANIMAL_OUTS AO
LEFT JOIN
    ANIMAL_INS AI
ON 
    AO.ANIMAL_ID = AI.ANIMAL_ID
WHERE AI.ANIMAL_ID IS NULL
ORDER BY AO.ANIMAL_ID ASC;