SELECT
    YEAR(A.SALES_DATE) AS YEAR,
    MONTH(A.SALES_DATE) AS MONTH,
    COUNT(DISTINCT A.USER_ID) AS PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT A.USER_ID) / (
            SELECT COUNT(*)
            FROM USER_INFO
            WHERE JOINED >= '2021-01-01'
              AND JOINED < '2022-01-01'
        ),
        1
    ) AS PUCHASED_RATIO
FROM ONLINE_SALE A
JOIN USER_INFO B ON A.USER_ID = B.USER_ID
WHERE B.JOINED >= '2021-01-01'
  AND B.JOINED < '2022-01-01'
GROUP BY YEAR(A.SALES_DATE), MONTH(A.SALES_DATE)
ORDER BY YEAR, MONTH;