-- 코드를 입력하세요
WITH FILTERED_CAR AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE
        START_DATE >= DATE '2022-08-01'
        AND START_DATE < DATE '2022-11-01'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
SELECT 
    TO_NUMBER(TO_CHAR(H.START_DATE, 'MM')) AS MONTH,
    H.CAR_ID,
    COUNT(*) AS RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN 
    FILTERED_CAR F
ON 
    H.CAR_ID = F.CAR_ID
WHERE
    H.START_DATE >= DATE '2022-08-01'
    AND H.START_DATE < DATE '2022-11-01'
GROUP BY 
    TO_CHAR(H.START_DATE, 'MM'),
    H.CAR_ID
ORDER BY 
    MONTH ASC,
    H.CAR_ID DESC;
