-- 코드를 입력하세요
SELECT 
    NAME,
    DATETIME
FROM 
    ANIMAL_INS AI
WHERE NOT EXISTS (
    SELECT 1
    FROM ANIMAL_OUTS AO
    WHERE AO.ANIMAL_ID = AI.ANIMAL_ID
)
ORDER BY AI.DATETIME ASC
FETCH FIRST 3 ROW ONLY;