-- 코드를 입력하세요
SELECT 
    DISTINCT CRCC.CAR_ID AS CAR_ID 
FROM
    CAR_RENTAL_COMPANY_CAR CRCC
JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
ON 
    CRCC.CAR_ID = CRCRH.CAR_ID 
WHERE 
    CRCC.CAR_TYPE = '세단' 
    AND CRCRH.START_DATE >= DATE '2022-10-01' 
    AND CRCRH.START_DATE < DATE '2022-11-01' 
ORDER BY CAR_ID DESC;

